name: Release

on: 
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    permissions:
      contents: write # for asset upload
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

#       # Get dependencies
#       - name: Get SVG with Classes
#         uses: actions/checkout@v4
#         with:
#           repository: vdelachaux/SVG-with-Classes
#           path: Components/SVG with Classes.4dbase

      - name: Build
        uses: 4d/build4d-action@main
        with:
          actions: "build,pack,archive"
          product-line: vcs
          version: vcs
          build: official
          token: ${{ secrets.DLTK }}

      - name: Upload
        run: |
          gh release upload ${{github.event.release.tag_name}} build/${{github.event.repository.name}}.zip
